version: "3"
services:
  
  api:
    build:
      context: ./backend
    #image: go-bin:latest
    container_name: gobin
    environment:
      - DB_ADDRESS=gobin-db
      - DB_PORT=5432
      - DB_USER=admin
      - DB_PASSWORD=8723
      - DB_NAME=go-bin_demo
      - GO_PORT=3002
   # env_file:
   #   - ./backend/.env
    ports:
      - 3002:3002
    restart: unless-stopped
    depends_on:
      - db    


  db:
    image: postgres:14
    container_name: gobin-db
    restart: unless-stopped
#    ports:
#      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 8723
      POSTGRES_DB: go-bin_demo
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]